dbprocessing/DButils.py, scripts/addFromConfig.py, tests_scripts/test_CreateDB.py, tests_scripts/test_addFromConfig.py, unit_tests/test_DButils.py
The `tests_scripts` directory contains unit tests for the scripts. Unfortunately these hadn't been updated in awhile and were failing. This PR fixes them, as well as making a small change so addFromConfig works properly with older config files (ones that don't explicitly specify code, inspector, and error directories.)
=> Fix unit tests for scripts

dbprocessing/DBstrings.py, dbprocessing/inspector.py, unit_tests/test_DBstrings.py, unit_tests/test_Inspector.py
@balarsen noticed that the inspector regex calculation was failing on some ECT files. These had file format arguments {APID} and {mday}, which dbprocessing has no special handling for, but it was quietly passing through to the inspector and the inspector was doing nice things with it. Once dbprocessing started calculating a regex from the file format, this failed.
This PR fixes things twice over:
1. It adds a regular expression for APID and mission day (mday). The APID is assumed lower-case hex, but we can recognize mix upper/lower. The mission day is assumed decimal but can be negative (we ran into that in the past...)
2. For any other file format strings that dbp doesn't recognize, it now replaces them with a catch-all regex when making the regex for the inspector.
Given that we don't …
=> Fix handling of inspector regex for ECT

unit_tests/test_DButils.py
test_DButils test_checkIncoming assumed that the incoming directory by default didn't exist, and thus would show no files to process. This wasn't guaranteed to be the case (#17). This PR sets the incoming dir before testing for empty, and then makes some files in that directory for a deterministic non-empty test (before it used the unit_tests directory and thus depended somewhat on what other files were in there.) Closes #17.
=> test_checkIncoming update to guarantee directory state (Closes #17)

dbprocessing/DButils.py, unit_tests/test_DButils.py
_getRequiredProducts called getInputProductID with a particular kwarg forcing return of the yesterday-count and tomorrow-count, which aren't in the old database. This PR tests the call with this kwarg and fixes on old databases, returning 0 for both yesterday and tomorrow, so downstream code should work just as it does for newer databases. Closes #20.
=> Fix _getRequiredProducts/getInputProductID on old DB (Closes #20)

.circleci/config.yml, docs/developer/github.rst, scripts/DBRunner.py
This PR sets up unit testing in CircleCI.
It documents the basic CircleCI/GitHub setup, for configuration which isn't in the .yaml (Closes #16).
It splits the build and the tests into separate jobs: the build which installs most dependencies and dbprocessing itself, the postgres test which installs the necessary postgres tools and creates the postgres db, and the unittest job which runs the unit tests (Closes #15). It uses workspace persistence to carry .local across (which catches all the Python installs, basically.)
It also clears out a few things we aren't currently using:
- It doesn't install vim, since it would need to do that for every job, slowing things down. vim can be installed from the command line after ssh in if something needs to be debugged.
- It removes the environment …
=> Run unit tests in CircleCI

dbprocessing/runMe.py, developer/README.txt, developer/functionals/no_inputs/README.txt, developer/functionals/no_inputs/inc_code_version.py, developer/functionals/no_inputs/no_inputs.conf, developer/functionals/no_inputs/root/dbp_codes/inspectors/inputless_inspector.py, developer/functionals/no_inputs/root/dbp_codes/scripts/inputless_v1.0.0/inputless_v1.0.0.py, docs/scripts.rst, scripts/DBRunner.py, unit_tests/test_DBRunner.py, unit_tests/test_runMe.py
NOTE: This PR conflicts with #24, in that it includes everything from #24. Either this can be merged and #24 closed, or when #24 is merged I'll rebase this one to the new master.
This PR enhances DBRunner in several ways:
- Allows execution of processes with no inputs
- Adds option to ingest the created files
- Adds option to bump the version to avoid DB conflicts, or only produce files which are out of date
This closes #9 by implementing the checklist/design there.
I had #24 open to get the testing-related changes out faster and hopefully have them reviewed before I did the functionality here. So if someone has time to review this one, it will get everything...if only a little time, then #24 can come first (and this one will have to wait for the rebase.)
=> DBRunner enhancements for ingest, update-only, force (Closes #9)

dbprocessing/DButils.py, docs/scripts.rst, scripts/CreateDB.py, scripts/CreateDBsabrs.py, scripts/MigrateDB.py, unit_tests/test_DButils.py
This PR speeds up the calculation of possible output files and thus closes #23. This works by JOINing the file table with a table containing Unix times and doing the search using that table. If that table doesn't exist, the old (slower) code will be used. Included is a script to migrate databases by adding this table and populating it with existing file entries; eventually this script can be expanded to perform other migration tasks (e.g. the yesterday/tomorrow columns) as part of #7.
No changelog entry since it doesn't exist, release notes pending (#28)
=> Speed up getFiles by start/stop time (Closes #23)

dbprocessing/DButils.py, unit_tests/test_DButils.py
`addFile` used to work if the `utc_start_time` or `utc_stop_time` were passed in as a `date` instead of `datetime`--it just put to midnight of that day. It's a little bit weird, but the inspector output tends to get passed straight to `addFile` and I managed to write a few inspectors that did this in some circumstances. I figured if I could make that mistake it might happen again. With #31 this no longer worked, since they were treated as datetimes before hitting the database. This PR explicitly converts to datetime.
=> addFile: fix utc_start_time/stop_time as dates with Unix time table

.circleci/config.yml
Our `createpostgres` job in CircleCI is failing on the `apt-get` of `postgresql-client`. The problem appears to be that the apt cache on the base CircleCI image isn't necessarily up-to-date, so it's trying to download packages that no longer are on the Debian mirrors, as in https://discuss.circleci.com/t/random-404-when-doing-apt-get-install-postgresql-client/30286
This is probably why #38 is not currently mergeable.
=> CircleCI: update apt cache before installing packages (fix CreateDBsabrs test)

dbprocessing/DButils.py, docs/scripts.rst, scripts/updateUnixTime.py, unit_tests/test_DButils.py
The Unix time table truncated start times for files to integer and used ceiling for end times. This means that a file with a timestamp late in the day (e.g. 23:59:59.600) could potentially be treated as if it had data in the next day, so for instance it would be passed in as an input for any processes that were using the next day. This PR does a truncate-to-integer in all cases, in both calculating the values for storage in the database and in converting datetimes to Unix time for lookup in the database.
Using an integer here is reasonable for speed (and not having to change database format yet again), and in general we don't operate with sub-second accuracy. We just need to do the Right Thing (or the Justifiable Thing) when there are sub-second timestamps. Because the beginning of a …
=> Fix Unix time table calculation to maintain file day

.circleci/config.yml, docs/conf.py
This PR adds a documentation build job to CircleCI to make sure the docs build without errors or warnings. This is helpful for catching errors in the documentation (as with the unit tests) but also cases where Sphinx might have changed, the intersphinx links aren't working, etc.
=> Build Sphinx docs in CI; check for warnings

.github/ISSUE_TEMPLATE/bugreport.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/pull_request_template.md, developer/README.txt, developer/scripts/git_notes.py, docs/developer/code_standards.rst, docs/developer/documentation.rst, docs/developer/index.rst, docs/developer/pull_requests.rst, docs/developer/release.rst, docs/index.rst, docs/release_notes.rst, docs/scripts.rst
This PR adds an initial release notes setup (closes #28), including auto-generated list of closed issues/PRs. That issue contains some example of the output and I suspect we might want to tweak the formatting a bit; it's fairly coarse.
It documents how to mark a PR ready for review (closes #30).
And it documents the Github magic words (closes #29). I think "closes" is probably the preferred word here because "fixes" seems less applicable to e.g. enhancement, but I'm open to objections. I'm also open to saying we don't have a standard, just use a word that does the closing. I also documented using them in both the PR and the commit; I think it helps tie everything together, but open to changing that.
This PR includes no dbprocessing functionality, but does include code to help prepare the …
=> More documentation of pull request processing; release notes

.circleci/config.yml, docs/developer/github.rst, docs/developer/pull_requests.rst
Add Docker authentication to images being pulled.
- [N/A] New code has inline comments where necessary
- [N/A] Any new modules, functions or classes have docstrings consistent with dbprocessing style
- [N/A] Major new functionality has appropriate Sphinx documentation
- [N/A] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [N/A] New features and bug fixes should have unit tests
Closes #32
=> add docker authentication

sphinx/Makefile
#1 moved the Sphinx source from the `sphinx/source` directory to `docs` to play better with GitHub. This also means the autosummary output goes in `docs`, but the `make clean` rule wasn't updated to remove old autosummary output from the new location. This PR fixes that.
=> Fix make clean for the autosummary docs

docs/release_notes.rst, docs/scripts.rst, scripts/linkUningested.py, unit_tests/test_all.py, unit_tests/test_linkUningested.py
This PR adds a new script which searches for files that are in their final location and match the filename format of a valid product, but have no records in the database. It then makes a symbolic link from that file into the incoming directory.
It's worth explaining the dbp feature that's behind this. Normally files are put into the incoming directory and dbprocessing puts them in their final location. But it's handy to be able to synchronize an entire tree (e.g. via rsync) and set up dbprocessing so that the "final location" of a file is exactly the place where it gets synced--then dbp doesn't need to move it, but definitely needs to ingest it so it's aware of the file. The way to do this is make a symbolic link in incoming that links to the file--then dbprocessing does the ingest and …
=> New linkUningested script: find files not in database and symlink for import

dbprocessing/runMe.py, docs/release_notes.rst, unit_tests/dbp_testing.py, unit_tests/test_dbprocessing.py, unit_tests/test_runMe.py
As discussed in #62, the interface version (x in x.y.z) of a file should be set entirely by the `output_interface_version` column in the code that creates it. #62 presents four problems in versioning, two of which (3 and 4 on that list) pertain to the interface version. This PR contains two changes to fix those problems.
One (3 from #62), if a code has its interface (major) version incremented, with no other changes (including no change to `output_interface_version`), its outputs become candidates for reprocessing and the reprocessed files will have an increment to the quality version. Without this PR, this would increment the interface version, and thus no longer match `output_interface_version`.
Two (4 from #62), if a file's interface (major) version is incremented, with no other …
=> Increment output quality versions when input/code interface version changes

dbprocessing/DButils.py, developer/functionals/postgresql/README.txt, docs/DButils.rst, docs/scripts.rst, scripts/CreateDB.py, scripts/addFromConfig.py, unit_tests/test_DButils.py
This is a start on #14 but by no means complete. It's an attempt to get us towards working PostgreSQL without having everything perfectly in order. In particular, it still uses the magic environment variables rather than completely generalizing the database URL.
This PR gets as far as being able to create the tables in a PostgreSQL database and start addFromConfig. Unfortunately there are some aspects of the behavior in dbUtils that are relying on sqlite, in particular weak type checking. I can do some work on that later but wanted to get this up for merge first so we don't duplicate effort. This should *not* affect current working sqlite setups.
There's no Sphinx documentation or release notes yet since the functionality isn't completed. Similarly for testing--there's a skeleton of a …
=> Minimal postgresql support in dbUtils

unit_tests/test_DBfile.py
This is a simple fix for test_DBfile. The included tests were working when called from `test_all.py`, but not when calling `test_DBfile.py` directly. The pathing is slightly different in those two cases and, in the latter case, it couldn't find the test data. Fixed by using the `dbp_testing` helper.
=> Fix test_DBfile when called by itself

.circleci/config.yml, scripts/CreateDBsabrs.py
SQLAlchemy quite some time ago (pre-0.6.0) renamed the `postgres` dialect to `postgresql` and recently (1.4) removed the compatibility for using the old name.  `CreateDBsabrs` was using the old name, so the CI now fails. This is why #72 is failing. `CreateDBsabrs` was also using the `reflect` kwarg for the `Metadata` constructor, deprecated since 0.8.
This PR fixes the name and the constructor call and also adds a workflow running nightly to catch this kind of change in the future without waiting for a PR to be opened.
=> Update postgresql dialect name in CreateDBsabrs

scripts/addFromConfig.py, unit_tests/data/configs/testDB_processNoOutputs.conf, unit_tests/test_addFromConfig.py
addFromConfig no longer works for processes with no output product on Python 2.7. This is due to a comparison of empty strings with "is" in a situation where one might be in Unicode. This comparison has been around for awhile--I think it only became a problem when some of the config file handling was consolidated into a single place, and not explicitly cast to str in Python 2.
This PR changes to a simple equality comparison. It also adds a unit test to addFromConfig for the no-output case. It's worth noting the unit test does _not_ catch the problem, as it's in the non-unit-tested (and not really easily testable) portion of addFromConfig. In lieu of that, I assert that the PSP config does not successfully load into a database with the previous addFromConfig, but does work with this PR. …
=> Fix addFromConfig for processes with no output product

.circleci/config.yml, dbprocessing/DButils.py, dbprocessing/Diskfile.py, dbprocessing/tables.py, scripts/addFromConfig.py, scripts/configFromDB.py, unit_tests/dbp_testing.py, unit_tests/test_DButils.py, unit_tests/test_addFromConfig.py, unit_tests/test_dbprocessing.py
New code is easier to review, integrate and maintain if it's
consistent with the style of the rest of the dbprocessing code.
Please try to follow as much of this checklist as you can for
your PR. If a given item is not relevant to your PR, please check
it off, add "(N/A)" to the start of the line, and include a
description below the checklist.
If you don't know how to complete something in the checklist, go
ahead and submit the PR as a draft and ask for help.
Some additional suggestions are given below.
Please also see our Code of Conduct so that the dbprocessing community
remains welcoming and inclusive.
Go ahead and replace the text above (and this line!) with your
pull request description.
add posgresql dialect and fix unit testings.   Some failure in testing are due to the other of …
=> add postgresql support and unit testing

dbprocessing/dbprocessing.py, docs/release_notes.rst, docs/scripts.rst, unit_tests/dbp_testing.py, unit_tests/test_dbprocessing.py
This PR changes `_getRequiredProducts` to only consider files that are recorded in the database as existing on disk, and thus won't try to use nonexistent files as inputs to processing. Closes #47.
I think I had speculated somewhere that the runMe checks of the command line build would catch trying to build with a nonexistent file. Turns out that's not the case, and I haven't chased that down.
#89 captures additional possible behavior changes that were incidentally mentioned in #47.
=>  Only use products that exist on disk when figuring inputs

scripts/fast_data.py
This one-liner fixes an issue with fast_data. It's intended to delete old versions of files but keep their records behind, while setting the exists_on_disk column to indicate it no longer exists.
The problem is with successive runs. It doesn't check this column before trying to delete, so it will delete files it's already deleted.
This PR adds a simple check for this flag and skips the deletion step if the database doesn't think the file exists. If the database thinks it exists and it's not actually there, it still errors--that's a consistentcy problem.
fast_data is currently untested (its functionality really needs to be wrapped up into main dbp), so there's no test on this.
=> fast_data: skip deleting files that don't exist on disk

.circleci/config.yml
CI is broken: docs won't build. It looks like `pip` is grabbing Sphinx 1.8.5, probably because we're doing the build on Python 2.7. That still gets a pretty new docutils (0.18). Unfortunately docutils changed some structures in 0.16 which made it incompatible with that Sphinx.
Long-term we're going to have to abandon Python 2 for the doc build (and maybe altogether; I was hoping to get out one Python 2 release but that may not happen). In the meantime I'm pinning to an earlier docutils for the CI.
=> Use docutils <0.16 when building docs in CI

docs/release_notes.rst, docs/scripts.rst, scripts/printProcessQueue.py
Adding options to printProcessQueue as we talked about. Closes #87.
* exist return 0 if there are files in processQueue otherwise 0
* count return the number of files in the processing queue.
* quiet option des not print any message on the screen.
Because this script isn't incorporated into unit tests yet, this was hand-tested.
=> add count/exist/quiet options to printProcessQueue

docs/release_notes.rst, docs/scripts.rst, scripts/printProcessQueue.py
This PR adds two options to `printProcessQueue` to help with scriptability.
The `-p`/`--product` option filters the output by product (either name or ID). This affects the output and also the `-c` and `-e` options. This doesn't just filter the output...it also adds a table of all the included products. So that does make parsing the output a little harder: basically everything up to the line that actually says "ProcessQueue" needs to be ignored.
The `-s`/`--sort` option sorts the output. Primary sort is by date, and secondary is by product _name_. I'm happy to switch this around to whatever is convenient for @dnadeau-lanl : making date secondary, doing product ID instead of name, etc.
Also, the HTML output mislabeled a column as "file ID"...it was a simple index (0, 1, 2....), not the file …
=> printProcessQueue: add ability to filter by product, sort

dbprocessing/DButils.py, unit_tests/test_DButils.py
This PR changes ``DButils.addProcess`` such that, if it is passed an empty string for the output product, it inserts null (``None``) into the database. This matches the handling of some other things which may be empty strings in the config file but null in the database, most notably extra arguments for processes. It fixes processes with no output product on postgresql and closes #95.
There is still some code in ``DButils.getChildTree`` to support databases (sqlite) where the column is an empty string, and those shouldn't be removed until #7 is closed (so that "version 1" database will not have the empty string there.)
I'm not making a release note entry because I'm considering this part of the greater project of getting postgres support going...this most likely would have been found, for …
=> Force empty output products to null (Closes #95)

unit_tests/test_DButils.py
Tiny PR relevant to discussion in #94, to clarifly the zero output product ID in a test is meant to verify the fix didn't introduce a regression, it's not actually a no-output process
=> test_DButils: clarify no-output tests

dbprocessing/DButils.py, dbprocessing/dbprocessing.py, dbprocessing/runMe.py, scripts/DBRunner.py
The `__del__` method of `DButils` tries to close the database (and log this closure) as a convenience for the user. Unfortunately if the `DButils` object is still hanging around at program termination, it will be deleted then, and the Python interpreter may have already torn down the logger, and potentially other facilities needed to close the database. The order in which things are torn down is not guaranteed.
This manifests in `DBRunner.py` since it fails to close the database. I've managed to whack-a-mole away most of the other instances but missed that one.
This PR:
- Fixes DBRunner to clean up before exit
- Adds documentation to `DButils` recommending cleaning up before exit, and also on `runMe` and `ProcessQueue`, since they hold references to `DButils`.
As this bug is …
=> Close DBrunner db on exit; document the need to close

dbprocessing/DButils.py, dbprocessing/Utils.py, dbprocessing/runMe.py, scripts/makeLatestSymlinks.py, scripts/newestVersionProblemFinder.py, unit_tests/dbp_testing.py, unit_tests/test_tables.py
This PR fixes deprecations for Python 3.9 (some of which would be errors in 3.10) and for sqlalchemy 1.4. Maintains support on earlier Python and sqlalchemy. Closes #83.
For Python 3.9/3.10:
- imports abstract base classes from `collections.abc` if possible (fallback to `collections`)
- Replaces `is` string comparisons with `==`
- A little bit of style cleanup in directly-related lines
For sqlalchemy 1.4:
- `table_names()` was removed (affects tests only)
- `mapped_table` was replaced with `persist_selectable` (affects tests only)
- Make a subquery into an explicit selection (`DButils`)
- Make a subquery into an explicitly scalar subquery (`newestVersionProblemFinder`, which is untested)
This supersedes #84, which does not fix all warnings in #83 and didn't preserve namespacing on …
=> Fix python 3.9 and sqlalchemy 1.4 deprecations

docs/CONTRIBUTING.rst, docs/README.rst, docs/SUPPORT.rst, docs/_templates/layout.html, docs/conf.py, docs/developer/documentation.rst, docs/index.rst
This PR provides a link to the GitHub page in the doc header and provides a "how to get support" page, thus closes #118. It also does a few general doc cleanups:
- Changes the HTML title (to "dbprocessing manual") and the title on the front docs page
- Add "dbprocessing" to the main header for each page
- Updates the README to include some language from the proposal that makes things a bit more clear, and adopt some language from the README for the front-page of the docs so it's not just a bullet list of doc titles.
=> Provide support documentation integrated with GitHub and other doc tweaks

docs/README.rst
#122 made it easier to get to the GitHub page from the website/built documentation. But from the GitHub page, the website isn't obvious. This PR just adds a link from the README so people looking at the repository can get linked to the built docs.
=> docs: link the website from README

docs/release_notes.rst
This PR contains two small changes to the 0.1.0 release notes. I don't intend to rebuild the website docs or release for 0.1.0 for these, but these make the history in there more accurate.
- #5 was closed and not included in the release notes, so that was added
- The final commit hashes for #123 and #124 obviously weren't available at the time the PRs were open, so added them now. This will always be a little bit of an issue, since the release notes "should" reference the PR with the final release, but putting the hash in the release notes will change the hash...for now I'm just thinking in terms of slapping in an update after the fact, like this, but there may be other options.
=> Update 0.1.0 release notes

.github/pull_request_template.md, developer/scripts/git_notes.py, docs/developer/github.rst, docs/developer/pull_requests.rst
This PR makes changes necessary to [rename the default branch from master to main](https://github.com/github/renaming) in accordance with current common practice. The actual rename will require me to make a small config change as well.
This is mostly documentation, and a small change to the release support scripts. No changes to dbprocessing functionality are included.
=> Rename default branch from master to main

.circleci/config.yml
As noted in #130 and #135, dbp currently uses the old syntax for SQLAlchemy which went away in 2.0. Short-term, all this PR does is keep the CI against pre-2.0 so that we're not dead in the water while working on #135.
=> CI: use sqlalchemy before 2.0
